# SPDX-License-Identifier: Elastic-2.0
# Copyright (c) 2026 Sergio Naval Marimont
"""Render the ClickHouse backup-disk config.d drop-in from the backup config.

The rendered XML is a build artifact of ``backup init`` — never hand-edited.
For an s3 destination the resolved writer credentials are inlined (ClickHouse
server config cannot read ``*_FILE`` references), so the output must be
written with restrictive permissions into the secrets-permissioned area and
mounted read-only. Rotation: update the secret files, re-run ``backup init``,
restart the clickhouse service.
"""
from __future__ import annotations

from xml.sax.saxutils import escape

from precis_mcp.backup import BackupConfigError
from precis_mcp.backup.config import BackupConfig, ResolvedCreds

BACKUP_DISK_NAME = "precis_backups"

# The store prefix CH artifacts land under, shared with the process-pushed
# artifacts so one destination root holds the whole bundle.
CH_PREFIX = "ch"


def s3_disk_endpoint(cfg: BackupConfig) -> str:
    """The full object URL the CH s3 disk writes under: endpoint/bucket/prefix/ch/."""
    d = cfg.destination
    base = (d.endpoint or f"https://s3.{d.region}.amazonaws.com").rstrip("/")
    parts = [base, d.bucket or ""]
    if d.prefix:
        parts.append(d.prefix)
    parts.append(CH_PREFIX)
    return "/".join(parts) + "/"


def local_disk_path(cfg: BackupConfig) -> str:
    """The CH-container path of the backup disk. Assumes the destination path
    is mounted identically in the clickhouse and backup containers."""
    return f"{(cfg.destination.path or '').rstrip('/')}/{CH_PREFIX}/"


def render_clickhouse_disk_xml(
    cfg: BackupConfig, creds: ResolvedCreds | None = None
) -> str:
    if cfg.destination.type == "local":
        disk_body = (
            f"            <type>local</type>\n"
            f"            <path>{escape(local_disk_path(cfg))}</path>\n"
        )
    elif cfg.destination.type == "s3":
        if creds is None:
            raise BackupConfigError(
                "rendering an s3 backup disk requires resolved writer credentials"
            )
        lines = [
            "            <type>s3</type>",
            f"            <endpoint>{escape(s3_disk_endpoint(cfg))}</endpoint>",
            f"            <access_key_id>{escape(creds.access_key_id)}</access_key_id>",
            f"            <secret_access_key>{escape(creds.secret_access_key)}</secret_access_key>",
        ]
        if cfg.destination.region:
            lines.append(f"            <region>{escape(cfg.destination.region)}</region>")
        disk_body = "\n".join(lines) + "\n"
    else:  # pragma: no cover — config validation rejects other types
        raise BackupConfigError(f"unsupported destination type {cfg.destination.type!r}")

    return (
        "<!-- GENERATED by `precis-mcp-admin backup init` from backup.yml — do not edit. -->\n"
        "<clickhouse>\n"
        "    <storage_configuration>\n"
        "        <disks>\n"
        f"            <{BACKUP_DISK_NAME}>\n"
        f"{disk_body}"
        f"            </{BACKUP_DISK_NAME}>\n"
        "        </disks>\n"
        "    </storage_configuration>\n"
        "    <backups>\n"
        f"        <allowed_disk>{BACKUP_DISK_NAME}</allowed_disk>\n"
        "    </backups>\n"
        "</clickhouse>\n"
    )
